### ISSUE TITLE
Also detect array like objects

### ISSUE THREAD

**Issue by sindresorhus** [Qix-/node-is-arrayish#1]
Like this one:

``` js
var arrayLikeObject = {
    length: 0,
    splice: function () {}
}
```

This is how jQuery makes it possible to do `$('.selector')[0]` btw.

http://stackoverflow.com/questions/11886578/creating-array-like-objects-in-javascript/11886626#11886626

**Comment by Qix-** [comment]
Landed in e411697d6bac9d16a284fa381d7c7b07817d8ddd and published as `0.2.0`.

Thanks! :+1:
